import type { BoardResponse } from "@/lib/types";

export const DEMO_BOARD_WAIVERS: BoardResponse = {
  view: "waivers",
  format: "category",
  commentary: {
    text: "Anthony Davis is the clear top pickup this week. Your league heavily rewards blocks and your roster is weak in both points and rebounds right now. Davis covers both at elite volume, and he draws four home games this week against soft frontcourt matchups.",
    fallback: false,
  },
  players: [
    {
      playerId: "ad",
      name: "Anthony Davis",
      position: "C",
      team: "LAL",
      rank: 1,
      score: 94.2,
      scoreLabel: "+8.3 cats",
      statLine: "25.4 pts · 12.6 reb · 2.4 blk · 1.3 stl",
      injuryStatus: null,
      tags: [
        { label: "Top pickup", tone: "hot" },
        { label: "4 games", tone: "good" },
      ],
      rankDelta: 3,
      otherFormatRank: 2,
      topCategories: [
        { label: "BLK", z: 3.8 },
        { label: "REB", z: 2.9 },
        { label: "PTS", z: 2.1 },
      ],
      buzz: 92,
    },
    {
      playerId: "js",
      name: "Jabari Smith Jr.",
      position: "PF",
      team: "HOU",
      rank: 2,
      score: 71.4,
      scoreLabel: "+5.1 cats",
      statLine: "16.2 pts · 8.1 reb · 1.8 blk · 1.0 stl",
      injuryStatus: null,
      tags: [{ label: "Trending", tone: "good" }],
      rankDelta: 7,
      otherFormatRank: 14,
      topCategories: [
        { label: "BLK", z: 2.1 },
        { label: "3PM", z: 1.8 },
      ],
      buzz: 74,
    },
    {
      playerId: "og",
      name: "OG Anunoby",
      position: "SF",
      team: "NYK",
      rank: 3,
      score: 68.9,
      scoreLabel: "+4.8 cats",
      statLine: "14.8 pts · 4.4 reb · 1.9 stl · 0.9 blk",
      injuryStatus: null,
      tags: [{ label: "Steals", tone: "good" }],
      rankDelta: 2,
      otherFormatRank: 18,
      topCategories: [
        { label: "STL", z: 2.6 },
        { label: "3PM", z: 1.4 },
      ],
      buzz: 61,
    },
    {
      playerId: "rh",
      name: "Richaun Holmes",
      position: "C",
      team: "DAL",
      rank: 4,
      score: 61.2,
      scoreLabel: "+3.9 cats",
      statLine: "11.4 pts · 9.2 reb · 1.6 blk · 0.6 stl",
      injuryStatus: null,
      tags: [{ label: "Streaming", tone: "good" }],
      rankDelta: -1,
      otherFormatRank: 31,
      topCategories: [
        { label: "REB", z: 2.2 },
        { label: "FG%", z: 1.9 },
      ],
      buzz: 44,
    },
    {
      playerId: "mk",
      name: "Maxi Kleber",
      position: "PF",
      team: "DAL",
      rank: 5,
      score: 54.7,
      scoreLabel: "+3.1 cats",
      statLine: "9.8 pts · 5.6 reb · 1.4 blk · 0.7 stl",
      injuryStatus: "QUESTIONABLE",
      tags: [{ label: "Injury risk", tone: "warn" }],
      rankDelta: -4,
      otherFormatRank: 44,
      topCategories: [
        { label: "3PM", z: 1.6 },
        { label: "BLK", z: 1.2 },
      ],
      buzz: 38,
    },
  ],
};

export const DEMO_BOARD_SLEEPERS: BoardResponse = {
  view: "sleepers",
  format: "category",
  commentary: {
    text: "Jalen Williams is the standout sleeper this week. His usage has climbed in five straight games since the Gilgeous-Alexander injury, and he is only rostered in 48% of leagues at your scoring level. If he is available, he is your highest-priority add.",
    fallback: false,
  },
  players: [
    {
      playerId: "jw",
      name: "Jalen Williams",
      position: "SG",
      team: "OKC",
      rank: 1,
      score: 81.3,
      scoreLabel: "+6.4 cats",
      statLine: "22.1 pts · 5.8 ast · 4.2 reb · 1.4 stl",
      injuryStatus: null,
      tags: [
        { label: "Usage spike", tone: "hot" },
        { label: "48% owned", tone: "good" },
      ],
      rankDelta: 12,
      otherFormatRank: 9,
      topCategories: [
        { label: "PTS", z: 2.8 },
        { label: "AST", z: 2.1 },
        { label: "STL", z: 1.6 },
      ],
      buzz: 88,
      reason: "Usage up 8% over last 5 games. Starting role locked in.",
    },
    {
      playerId: "tb",
      name: "Tari Eason",
      position: "PF",
      team: "HOU",
      rank: 2,
      score: 62.4,
      scoreLabel: "+4.2 cats",
      statLine: "13.6 pts · 6.8 reb · 1.8 stl · 0.8 blk",
      injuryStatus: null,
      tags: [{ label: "Role growing", tone: "good" }],
      rankDelta: 9,
      otherFormatRank: 28,
      topCategories: [
        { label: "STL", z: 2.4 },
        { label: "REB", z: 1.7 },
      ],
      buzz: 71,
      reason: "Minutes up to 31 per game over last week.",
    },
  ],
};

export const DEMO_BOARD_ROSTER: BoardResponse = {
  view: "roster",
  format: "category",
  team: { rosterId: 1, teamName: "Your Team", ownerName: "You" },
  commentary: null,
  players: [
    {
      playerId: "lj",
      name: "LeBron James",
      position: "SF",
      team: "LAL",
      rank: 4,
      score: 88.1,
      scoreLabel: "+7.1 cats",
      statLine: "24.8 pts · 7.4 ast · 7.1 reb · 1.3 stl",
      injuryStatus: null,
      tags: [{ label: "Anchor", tone: "hot" }],
      rankDelta: 0,
      otherFormatRank: 3,
      topCategories: [
        { label: "PTS", z: 2.4 },
        { label: "AST", z: 2.8 },
        { label: "REB", z: 1.6 },
      ],
      buzz: 79,
    },
    {
      playerId: "jt",
      name: "Jayson Tatum",
      position: "SF",
      team: "BOS",
      rank: 7,
      score: 82.4,
      scoreLabel: "+6.2 cats",
      statLine: "27.1 pts · 8.2 reb · 4.4 ast · 1.1 stl",
      injuryStatus: null,
      tags: [{ label: "Core", tone: "good" }],
      rankDelta: 1,
      otherFormatRank: 6,
      topCategories: [
        { label: "PTS", z: 3.1 },
        { label: "REB", z: 1.8 },
      ],
      buzz: 65,
    },
    {
      playerId: "de",
      name: "De'Aaron Fox",
      position: "PG",
      team: "SAC",
      rank: 18,
      score: 66.2,
      scoreLabel: "+4.1 cats",
      statLine: "24.2 pts · 5.8 ast · 3.4 reb · 1.6 stl",
      injuryStatus: null,
      tags: [{ label: "Solid", tone: "good" }],
      rankDelta: -2,
      otherFormatRank: 22,
      topCategories: [
        { label: "STL", z: 2.1 },
        { label: "PTS", z: 1.9 },
      ],
      buzz: 51,
    },
    {
      playerId: "bm",
      name: "Brook Lopez",
      position: "C",
      team: "MIL",
      rank: 34,
      score: 48.1,
      scoreLabel: "+2.4 cats",
      statLine: "12.4 pts · 4.8 reb · 2.6 blk · 0.6 stl",
      injuryStatus: "QUESTIONABLE",
      tags: [{ label: "Injury risk", tone: "warn" }],
      rankDelta: -6,
      otherFormatRank: 41,
      topCategories: [
        { label: "BLK", z: 3.2 },
        { label: "3PM", z: 1.4 },
      ],
      buzz: 42,
    },
  ],
};

import type { TradeResponse, BoardResponse } from "@/lib/types";

export const DEMO_TRADE: TradeResponse = {
  found: true,
  format: "category",
  partnerTeamName: "Hoop Dreams",
  give: {
    playerId: "de",
    name: "De'Aaron Fox",
    position: "PG",
    team: "SAC",
    rank: 18,
    score: 66.2,
    scoreLabel: "+4.1 cats",
    statLine: "24.2 pts · 5.8 ast · 3.4 reb · 1.6 stl",
    injuryStatus: null,
    tags: [{ label: "Solid", tone: "good" }],
    rankDelta: -2,
    otherFormatRank: 22,
    topCategories: [
      { label: "STL", z: 2.1 },
      { label: "PTS", z: 1.9 },
    ],
    buzz: 51,
  },
  receive: {
    playerId: "ad",
    name: "Anthony Davis",
    position: "C",
    team: "LAL",
    rank: 1,
    score: 94.2,
    scoreLabel: "+8.3 cats",
    statLine: "25.4 pts · 12.6 reb · 2.4 blk · 1.3 stl",
    injuryStatus: null,
    tags: [
      { label: "Top pickup", tone: "hot" },
      { label: "4 games", tone: "good" },
    ],
    rankDelta: 3,
    otherFormatRank: 2,
    topCategories: [
      { label: "BLK", z: 3.8 },
      { label: "REB", z: 2.9 },
      { label: "PTS", z: 2.1 },
    ],
    buzz: 92,
  },
  userNeed: "blocks and rebounds",
  partnerNeed: "assists and steals",
  fairness: "you-gain-value",
  commentary: {
    text: "This trade works because your roster is elite in assists and steals but ranks near the bottom in blocks and rebounds. Hoop Dreams has the opposite problem. Davis fills your two weakest categories at an elite level, and Fox is a fair price — he is your fourth-best player but their biggest need.",
    fallback: false,
  },
};

export const DEMO_ROSTER_PARTNER: BoardResponse = {
  view: "roster",
  format: "category",
  team: { rosterId: 2, teamName: "Hoop Dreams", ownerName: "Alex" },
  commentary: null,
  players: [
    {
      playerId: "ad",
      name: "Anthony Davis",
      position: "C",
      team: "LAL",
      rank: 1,
      score: 94.2,
      scoreLabel: "+8.3 cats",
      statLine: "25.4 pts · 12.6 reb · 2.4 blk · 1.3 stl",
      injuryStatus: null,
      tags: [{ label: "Anchor", tone: "hot" }],
      rankDelta: 3,
      otherFormatRank: 2,
      topCategories: [
        { label: "BLK", z: 3.8 },
        { label: "REB", z: 2.9 },
      ],
      buzz: 92,
    },
    {
      playerId: "sh",
      name: "Shai Gilgeous-Alexander",
      position: "PG",
      team: "OKC",
      rank: 2,
      score: 91.1,
      scoreLabel: "+7.8 cats",
      statLine: "30.1 pts · 5.5 ast · 4.8 reb · 2.1 stl",
      injuryStatus: null,
      tags: [{ label: "Core", tone: "hot" }],
      rankDelta: 0,
      otherFormatRank: 1,
      topCategories: [
        { label: "PTS", z: 3.6 },
        { label: "STL", z: 2.4 },
      ],
      buzz: 88,
    },
    {
      playerId: "kd",
      name: "Kevin Durant",
      position: "SF",
      team: "PHX",
      rank: 9,
      score: 79.4,
      scoreLabel: "+5.9 cats",
      statLine: "27.3 pts · 6.6 reb · 5.0 ast · 0.9 stl",
      injuryStatus: null,
      tags: [{ label: "Solid", tone: "good" }],
      rankDelta: -1,
      otherFormatRank: 7,
      topCategories: [
        { label: "PTS", z: 3.1 },
        { label: "REB", z: 1.4 },
      ],
      buzz: 72,
    },
  ],
};